language: python
python:
  - "2.7"
install:
  - pip install -r requirements.txt
  - pip install -r testing_requirements.txt
  - export PYTHONPATH=$PYTHONPATH:`pwd`/demotime
script:
  - python dt/manage.py test
notifications:
  email:
    recipients:
      - f4nt@f4ntasmic.com
